name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
        
      - name: Build
        run: |
          pip install pandas pyautogui pyinstaller openpyxl nbconvert
          
          # 1. Converte o notebook. Usamos aspas por causa do acento e --output para normalizar o nome
          jupyter nbconvert --to script "relatório.ipynb" --output relatorio
          
          # 2. Gera o executável a partir do 'relatorio.py' criado pelo comando acima
          pyinstaller --onefile --hidden-import=openpyxl relatorio.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: possibilidade-alocacao
          path: dist/*.exe